services:
  react-app:
    build: .
    container_name: bateponto_react
    image: bateponto:1.0
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
      resources:
        limits:
          memory: 1G
